- name: Install Asterisk
  apt: name={{ item }} update_cache=yes state=present
  sudo: yes
  with_items:
  - asterisk

- name: Stopping asterisk
  service:
    name: asterisk
    state: stopped

- name: copy files
  command: cp -r /home/vagrant/asterisk/{{ item }} /etc/asterisk/
  with_items:
   - "sip.conf"
   - "extensions.conf"
   - "queues.conf"
   - "modules.conf"
   - "iax.conf"
   - "voicemail.conf"


- unarchive:
    src: https://www.voipnovatos.es/voces/voipnovatos-extra-sounds-es-alaw-1.4.tar.gz
    dest: /usr/share/asterisk/sounds/
    remote_src: True

- unarchive:
    src: https://www.voipnovatos.es/voces/voipnovatos-core-sounds-es-alaw-1.4.tar.gz
    dest: /usr/share/asterisk/sounds/
    remote_src: True



- name: Restarting asterisk
  service:
    name: asterisk
    state: started
